version: "2"
services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_online_converter
    stdin_open: true
    tty: true
    volumes:
      - .:/online_converter
    ports:
      - "8000:8000"