# Generated by Django 2.2.2 on 2019-06-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='link')),
                ('date_load', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
